/**
 * Ecommerce API
 * Documentation of Ecommerce API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Link } from './link';


export interface EntityModelOrder { 
    price?: number;
    status?: EntityModelOrder.StatusEnum;
    userId?: string;
    dateCreated?: number;
    lastUpdated?: number;
    _links?: { [key: string]: Link; };
}
export namespace EntityModelOrder {
    export type StatusEnum = 'CART' | 'COMPLETED';
    export const StatusEnum = {
        Cart: 'CART' as StatusEnum,
        Completed: 'COMPLETED' as StatusEnum
    };
}


