/**
 * Ecommerce API
 * Documentation of Ecommerce API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Product } from './product';


export interface Order { 
    id?: number;
    price?: number;
    status?: Order.StatusEnum;
    userId?: string;
    dateCreated?: number;
    lastUpdated?: number;
    product?: Product;
}
export namespace Order {
    export type StatusEnum = 'CART' | 'COMPLETED';
    export const StatusEnum = {
        Cart: 'CART' as StatusEnum,
        Completed: 'COMPLETED' as StatusEnum
    };
}


