/**
 * Ecommerce API
 * Documentation of Ecommerce API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageMetadata } from './pageMetadata';
import { PagedModelEntityModelProductEmbedded } from './pagedModelEntityModelProductEmbedded';
import { Link } from './link';


export interface PagedModelEntityModelProduct { 
    _embedded?: PagedModelEntityModelProductEmbedded;
    _links?: { [key: string]: Link; };
    page?: PageMetadata;
}

