version: "3.8"

services:
  ecommerce-mysql:
    image: mysql:8.0.29
    container_name: ecommerce-mysql
    restart: always
    networks:
      - proxy
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=full-stack-ecommerce
      - MYSQL_USER=ecommerce
      - MYSQL_PASSWORD=ecommerce
  ecommerce-server:
    container_name: ecommerce-server
    depends_on:
      - ecommerce-mysql
    build: ./server
    restart: always
    environment:
      - spring.datasource.url=jdbc:mysql://ecommerce-mysql:3306/full-stack-ecommerce?useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true
      - spring.datasource.username=ecommerce
      - spring.datasource.password=ecommerce
    networks:
      - proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.ecommerce-server.rule=Host(`ecommerce.myngz.com`) && PathPrefix(`/api`)'
      - 'traefik.http.routers.ecommerce-server.entrypoints=websecure'
      - 'traefik.http.routers.ecommerce-server.tls.certresolver=letsencrypt'
      - 'traefik.http.services.ecommerce-server.loadbalancer.server.port=8080'
  ecommerce-web:
    container_name: ecommerce-web
    build: ./web
    restart: always
    networks:
      - proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.ecommerce-web.rule=Host(`ecommerce.myngz.com`)'
      - 'traefik.http.routers.ecommerce-web.entrypoints=websecure'
      - 'traefik.http.routers.ecommerce-web.tls.certresolver=letsencrypt'

networks:
  proxy:
    external: false
    name: proxy
