version: "3.8"

services:
  ecommerce-mysql:
    image: mysql:8.0.29
    container_name: ecommerce-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=full-stack-ecommerce
      - MYSQL_USER=ecommerce
      - MYSQL_PASSWORD=ecommerce
    ports:
      - 3306:3306
  ecommerce-server:
    container_name: ecommerce-server
    depends_on:
      - ecommerce-mysql
    build: ./server
    restart: on-failure
    environment:      
      - spring.datasource.url=jdbc:mysql://ecommerce-mysql:3306/full-stack-ecommerce?useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true
      - spring.datasource.username=ecommerce
      - spring.datasource.password=ecommerce
    ports:
      - 8080:8080
  ecommerce-web:
    container_name: ecommerce-web
    build: ./web
    restart: on-failure
    ports:
      - 4200:80
