name: Docker Prod

on:
    workflow_dispatch:
    push:
        branches: [ master ]
concurrency:
    group: ${{ github.ref }}
    cancel-in-progress: true
jobs:
    build:
        runs-on: self-hosted

        steps:
            -   uses: actions/checkout@v4

            -   name: Create env file
                run: |
                    echo KEYCLOAK_ADMIN_PASSWORD=${{ secrets.KEYCLOAK_ADMIN_PASSWORD }} > .env
                    echo KEYCLOAK_URL=${{ secrets.KEYCLOAK_URL }} >> .env
                    echo KEYCLOAK_HOST=${{ secrets.KEYCLOAK_HOST }} >> .env
                    echo KEYCLOAK_REALM=${{ secrets.KEYCLOAK_REALM }} >> .env
                    
                    echo LOCALHOST_URL=${{ secrets.LOCALHOST_URL }} >> .env
                    echo PUBLIC_URL=${{ secrets.PUBLIC_URL }} >> .env
                    
                    echo SPRING_DATASOURCE_DATABASE=${{ secrets.SPRING_DATASOURCE_DATABASE }} >> .env
                    echo SPRING_DATASOURCE_HOST=${{ secrets.SPRING_DATASOURCE_HOST }} >> .env
                    echo SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }} >> .env
                    echo SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }} >> .env

            -   name: Edit keycloak realm configuration
                run: |
                    sed -i 's|http://localhost:8080|https://${{ secrets.PUBLIC_URL }}/api|g' keycloak/ecommerce-realm.json
                    sed -i 's|http://localhost:4200|https://${{ secrets.PUBLIC_URL }}|g' keycloak/ecommerce-realm.json

            -   name: Reset DB
                run: docker stop ecommerce-postgres || true && docker rm ecommerce-postgres || true

            -   name: Reset Keycloak
                run: docker stop ecommerce-keycloak || true && docker rm ecommerce-keycloak || true

            -   name: Rename and overwrite docker-compose file
                run: mv docker-compose-prod.yml docker-compose.yml
                
            -   name: Docker run
                run: docker compose up -d --force-recreate --build
